bdd/urls.py
from django.conf.urls import url, handler404, handler500
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from quant import coin_views
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

static_view = never_cache(serve)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('users/', include('users.urls')),
    path('coins/', coin_views.index),
    path('q/<str:exchange>/', include('quant.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('logout_site/', views.logout_site, name='logout'),
]

bdd/models.py
from datetime import datetime
from django.db import models
from users.models import UserProfile
from django.db.models import Avg, Count, Min, Sum

bdd/views.py
import os
import uuid
import string
import pprint
from ipware import get_client_ip
import logging
from django.http import Http404
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.admin.views.decorators import staff_member_required
from django.template import RequestContext
from django_user_agents.utils import get_user_agent
from quant.models import Ohlcv, Coin, Signal
from bdd import settings
from users.models import UserProfile, SmsCaptcha

def index(request):
    return render(request, 'bdd/index.html')

bdd/templates/bdd/alerts.html
<div id='error-alert' class="alert alert-danger alert-dismissible d-none" role="alert" data-dismiss="alert">
  <span class='msg'></span>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div id='notice-alert' class="alert alert-primary alert-dismissible d-none" role="alert" data-dismiss="alert">
  <span class='msg'></span>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger alert-dismissible">
                <strong>{{ field.label }}: {{ error|escape }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissible">
            <strong>{{ error|escape }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}

bdd/templates/bdd/head.html
{% load staticfiles %}
{% load sass_tags %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <title>蚁单</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}" />
</head>

bdd/templates/bdd/header.html
{% load staticfiles %}
{% load i18n %}
<div class="user-header">
  <div class="header-one">
    <div class="header-logo">
      <a href='/'>
          <img src="{% static 'image/logo.png' %}" class="one-logo" width="40"/>
      </a>
    </div>
    <nav class="header-two">
      {% if request.user.is_authenticated %}
      <li class="hli-1">
        <a class="header-users" href="#"></a>
      </li>
      <li class="hli-2">
        <a class="header-menu1" href="#">{{ request.user.mobile }}</a>
      </li>
      <li class="hli-3">
        <a href="{% url 'users:logout' %}" class="login one-a small">{% trans 'logout' %}</a>
        <div class="btn-group language d-none">
          <button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn btn-default dropdown-toggle">
            English
            <span class="caret"></span>
             </button>
             <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="javascript:void(0);">English</a></li>
              <li><a href="javascript:void(0);">繁體中文</a></li>
              <li><a href="javascript:void(0);">한국어</a></li>
              <li><a href="javascript:void(0);">Français</a></li>
             </ul>
          </div>
      </li>
      {% else %}

      {% endif %}
    </nav>
  </div>
</div>

bdd/templates/bdd/index.html
{% load staticfiles %}
{% load sass_tags %}
{# Display django.contrib.messages as Bootstrap alerts #}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title></title>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/alertify.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/intlTelInput.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plotly-latest.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
  </head>
  <body class="base-page">
    <div class='container-fluid'>
      <h3>BitTrade</h3>
      {% block content %}{% endblock content %}
    </div>
  </body>
</html>